name: AuctionHouse
api: [3.9.0, 3.9.1, 3.9.2]
main: RyanTheOwner\AuctionHouse
version: 1.1
author: RyanTheOwner, peptiGamer
commands:
  ah:
    description: ""
    aliases: ["auction", "auctionhouse"]
